Repository wghglory/ngx-lift, pull requests merged in 2024-02, with the labels that each got.

#17 fix: avoid annoying error message in UT
  projects/ngx-extension/src/lib/operators/create-async-state.operator.spec.ts
Labels: test

#18 refactor(operator): refactor the combine-latest-eager operator by extracting function
  projects/ngx-extension/src/lib/operators/combine-latest-eager.operator.ts
Labels: enhancement

#19 docs: support angular 15 as minimum version
  README.md
  package.json
  projects/clr-extension/README.md
  projects/clr-extension/package.json
  projects/demo-application/src/app/clr-lib/pages/clr-extension-home/clr-extension-home.component.html
  projects/demo-application/src/app/clr-lib/pages/clr-extension-home/clr-extension-home.component.ts
  projects/demo-application/src/app/ngx-lib/pages/ngx-extension-home/ngx-extension-home.component.html
  projects/ngx-extension/README.md
  projects/ngx-extension/package.json
  projects/ngx-extension/src/lib/operators/create-async-state.operator.ts
Labels: documentation

#22 feat(component): add timeline wizard component
  projects/clr-extension/package.json
  projects/clr-extension/src/lib/components/index.ts
  projects/clr-extension/src/lib/components/key-value-inputs/key-value-inputs.component.html
  projects/clr-extension/src/lib/components/timeline-wizard/index.ts
  projects/clr-extension/src/lib/components/timeline-wizard/timeline-base.component.ts
  projects/clr-extension/src/lib/components/timeline-wizard/timeline-step.type.ts
  projects/clr-extension/src/lib/components/timeline-wizard/timeline-wizard.component.html
  projects/clr-extension/src/lib/components/timeline-wizard/timeline-wizard.component.scss
  projects/clr-extension/src/lib/components/timeline-wizard/timeline-wizard.component.spec.ts
  projects/clr-extension/src/lib/components/timeline-wizard/timeline-wizard.component.ts
  projects/clr-extension/src/lib/components/timeline-wizard/timeline-wizard.l10n.ts
  projects/clr-extension/src/lib/components/timeline-wizard/timeline-wizard.service.spec.ts
  projects/clr-extension/src/lib/components/timeline-wizard/timeline-wizard.service.ts
  projects/demo-application/src/app/app.routes.ts
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/configure-operator/configure-operator.component.html
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/configure-operator/configure-operator.component.scss
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/configure-operator/configure-operator.component.spec.ts
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/configure-operator/configure-operator.component.ts
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/configure-review/configure-review.component.html
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/configure-review/configure-review.component.scss
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/configure-review/configure-review.component.spec.ts
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/configure-review/configure-review.component.ts
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/configure-runtime-prop/configure-runtime-prop.component.html
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/configure-runtime-prop/configure-runtime-prop.component.scss
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/configure-runtime-prop/configure-runtime-prop.component.spec.ts
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/configure-runtime-prop/configure-runtime-prop.component.ts
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/configure-service/configure-service.component.html
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/configure-service/configure-service.component.scss
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/configure-service/configure-service.component.spec.ts
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/configure-service/configure-service.component.ts
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/deployment.type.ts
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/timeline-wizard-demo.component.html
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/timeline-wizard-demo.component.scss
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/timeline-wizard-demo.component.spec.ts
  projects/demo-application/src/app/clr-lib/pages/timeline-wizard-demo/timeline-wizard-demo.component.ts
  projects/demo-application/src/app/core/components/vertical-nav/vertical-nav.const.ts
Labels: enhancement

#28 feat: add is https pipe, url validator, https validator
  projects/demo-application/src/app/app.routes.ts
  projects/demo-application/src/app/core/components/vertical-nav/vertical-nav.const.ts
  projects/demo-application/src/app/ngx-lib/pages/pipes/is-https-pipe/is-https-pipe.component.html
  projects/demo-application/src/app/ngx-lib/pages/pipes/is-https-pipe/is-https-pipe.component.scss
  projects/demo-application/src/app/ngx-lib/pages/pipes/is-https-pipe/is-https-pipe.component.spec.ts
  projects/demo-application/src/app/ngx-lib/pages/pipes/is-https-pipe/is-https-pipe.component.ts
  projects/demo-application/src/app/ngx-lib/pages/validators/url-validator/url-validator.component.html
  projects/demo-application/src/app/ngx-lib/pages/validators/url-validator/url-validator.component.scss
  projects/demo-application/src/app/ngx-lib/pages/validators/url-validator/url-validator.component.spec.ts
  projects/demo-application/src/app/ngx-lib/pages/validators/url-validator/url-validator.component.ts
  projects/ngx-extension/package.json
  projects/ngx-extension/src/lib/const.ts
  projects/ngx-extension/src/lib/pipes/index.ts
  projects/ngx-extension/src/lib/pipes/is-https.pipe.spec.ts
  projects/ngx-extension/src/lib/pipes/is-https.pipe.ts
  projects/ngx-extension/src/lib/validators/index.ts
  projects/ngx-extension/src/lib/validators/url.validator.spec.ts
  projects/ngx-extension/src/lib/validators/url.validator.ts
Labels: enhancement

#27 refactor(validator): refactor unique-validator using setErrors
  projects/demo-application/src/app/ngx-lib/pages/validators/unique-validator/unique-validator.component.ts
  projects/ngx-extension/src/lib/validators/unique.validator.spec.ts
  projects/ngx-extension/src/lib/validators/unique.validator.ts
Labels: enhancement

#29 feat(pipe): add mask pipe
  projects/demo-application/src/app/app.routes.ts
  projects/demo-application/src/app/core/components/vertical-nav/vertical-nav.const.ts
  projects/demo-application/src/app/ngx-lib/pages/pipes/mask-pipe/mask-pipe.component.html
  projects/demo-application/src/app/ngx-lib/pages/pipes/mask-pipe/mask-pipe.component.scss
  projects/demo-application/src/app/ngx-lib/pages/pipes/mask-pipe/mask-pipe.component.spec.ts
  projects/demo-application/src/app/ngx-lib/pages/pipes/mask-pipe/mask-pipe.component.ts
  projects/ngx-extension/src/lib/pipes/index.ts
  projects/ngx-extension/src/lib/pipes/mask.pipe.spec.ts
  projects/ngx-extension/src/lib/pipes/mask.pipe.ts
Labels: enhancement

#30 fix(operator): fix switchMapWithAsyncState loading
  projects/ngx-extension/src/lib/operators/switch-map-with-async-state.operator.ts
Labels: bug

#31 feat: add form ifValidator and ifAsyncValidator utils
  projects/demo-application/src/app/app.routes.ts
  projects/demo-application/src/app/core/components/vertical-nav/vertical-nav.const.ts
  projects/demo-application/src/app/ngx-lib/pages/validators/if-validator/if-validator.component.html
  projects/demo-application/src/app/ngx-lib/pages/validators/if-validator/if-validator.component.scss
  projects/demo-application/src/app/ngx-lib/pages/validators/if-validator/if-validator.component.spec.ts
  projects/demo-application/src/app/ngx-lib/pages/validators/if-validator/if-validator.component.ts
  projects/ngx-extension/package.json
  projects/ngx-extension/src/lib/utils/form.util.spec.ts
  projects/ngx-extension/src/lib/utils/form.util.ts
  projects/ngx-extension/src/lib/utils/index.ts
Labels: enhancement
